[package]
name = "fedora-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
cmd_lib = "1.3"
nix = { version = "0.30.1", features = ["user"] }
tempfile = "3.8"
